language: ruby

services:
  - docker

before_install:
  - docker pull v7lin/flutter:1.0.0-stable

jobs:
  include:
  - stage: format
    script:
      - docker run --rm -v ${PWD}:/fake_http v7lin/flutter:1.0.0-stable sh -c "cd /fake_http && flutter packages get && flutter format --dry-run --set-exit-if-changed ."
  - stage: analyze
    script:
      - docker run --rm -v ${PWD}:/fake_http v7lin/flutter:1.0.0-stable sh -c "cd /fake_http && flutter packages get && flutter analyze"
  - stage: test
    script:
      - docker run --rm -v ${PWD}:/fake_http v7lin/flutter:1.0.0-stable sh -c "cd /fake_http && flutter packages get && flutter test"
  - stage: publish-check
    script:
      - docker run --rm -v ${PWD}:/fake_http v7lin/flutter:1.0.0-stable sh -c "cd /fake_http && flutter packages get && flutter packages pub publish --dry-run"
