name: okhttp_kit
description: A powerful http package for Dart/Flutter.
version: 1.0.2
author: v7lin <v7lin@qq.com>
homepage: https://github.com/v7lin/fake_okhttp

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  charcode: ^1.1.2
  convert: ^2.1.1
  crypto: ^2.0.6
  fixnum: ^0.10.9
  path: ^1.6.2

dev_dependencies:
  test: ^1.0.0

  pedantic:
