name: fake_okhttp
description: A powerful http package for Dart/Flutter.
version: 0.2.0
author: v7lin <v7lin@qq.com>
homepage: https://github.com/v7lin/fake_okhttp

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: '>=1.1.6 <2.0.0'
  charcode: '>=1.1.2 <2.0.0'
  convert: '>=2.1.1 <3.0.0'
  crypto: '>=2.0.6 <3.0.0'
  fixnum: '>=0.10.9 <1.0.0'
  path: ">=1.6.2 <2.0.0"

dev_dependencies:
  test: ^1.0.0

  pedantic: '>=1.4.0 <3.0.0'
